import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "./components/Navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { AuthPage } from "./components/AuthPage"
import { Routes, Route } from 'react-router-dom';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="flex h-screen flex-col bg-[#0B0D17] text-gray-100">
            <main className="flex-1 overflow-y-auto p-6">
              <header className="flex justify-end items-center p-4 gap-4 h-16">
                <SignedOut>
                  <SignInButton className="sign-in-button border-[1px] border-gray-500 py-2 px-4 rounded-lg" />
                  <SignUpButton className="sign-in-button border-[1px] border-gray-500 py-2 px-4 rounded-lg" />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </header>
              <SidebarProvider>
                <AppSidebar />
                <main>
                  <SidebarTrigger />
                  <div className="mx-50">
                    {children}
                  </div>
                </main>
              </SidebarProvider>
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}